apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  # Uncomment the line below if using step-ca for internal CA setup instead of public Let's Encrypt
  # - ../../step-ca