apiVersion: v1
kind: Service
metadata:
  name: graphrag-server
  namespace: graphrag-kotaemon-ui
  labels:
    app: graphrag-server
spec:
  selector:
    app: graphrag-server
  ports:
  - port: 20213
    targetPort: 20213
    protocol: TCP
    name: http
  type: ClusterIP